### ISSUE TITLE
Question regarding using pulp_axi

### ISSUE THREAD

**Issue by hossein1387** [pulp-platform/axi#173]
I am planning to use `pulp_axi` module for an interface between CSRs of my RISC-V processor and an accelerator. The idea here is to control the accelerator with the configuration registers that are set by SW in the CSR module. 

1. I was wondering which `axi` interface do you recommend? 
2. Also, what are the minimum `pulp` blocks I need to use?
3. Finally I am planning to implement my system on a Xilinx FPGA and since I might move toward ASIC implementation, do you recommend to use Xilinx IPs for FPGA and your IPs for ASIC or can I use your IPS for both scenario?

**Comment by accuminium** [comment]
Hi @hossein1387, thanks for your questions.

> 1. I was wondering which axi interface do you recommend?

For reading and writing a few control registers, AXI4-Lite should do.  It should be fairly straightforward to write a module that translates the memory "protocol" of your processor's LSU to AXI4-Lite.

> 2. Also, what are the minimum pulp blocks I need to use?

[This repository currently depends](https://github.com/pulp-platform/axi/blob/v0.29.0/Bender.yml#L11) on [`v1.21.0` of `pulp-platform/common_cells`](https://github.com/pulp-platform/common_cells/tree/v1.21.0).  There are no other dependencies for using the AXI modules.

> 3. Finally I am planning to implement my system on a Xilinx FPGA and since I might move toward ASIC implementation, do you recommend to use Xilinx IPs for FPGA and your IPs for ASIC or can I use your IPS for both scenario?

I would use the same IPs on the FPGA and the ASIC, simply because it reduces the differences between ASIC and FPGA.  The more of your hardware is exactly the same (at least in terms of RTL code) on FPGA and ASIC, the more you can verify and prototype on the FPGA before tapeout, and the higher confidence you can have that your RTL does not have major flaws.
